
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Navbar from "@/components/Navbar";
import SideNav from "@/components/sidenav/SideNav";
import QuickActions from "@/components/quickActions/QuickActions";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
            <Navbar />
          <div className="  overflow-x-hidden flex flex-col  ">
            <div className="flex ">
            <SideNav />

            <div className="">{children}</div>
            </div>
          <Footer/>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
